### ISSUE TITLE
Not able to execute the statement

### ISSUE THREAD

**Issue by malikdaman24** [Praqma/git-metrics#6]
I tried running below commands, but did not get the output. Can you please help me with the issue? It would help if you can provide a sample or an example? I might be not providing the correct inputs.

python git_metrics.py release-lead-time [--tag-pattern=v*] [--earliest-date=10-06-2020] https://github.com/malikdaman24/test_metrics > repo_data.csv

It would really help if by giving an example you can explain what logic have been used to calculate all these metrics; as people like me who are not good technically, can use this to better understand the output.

**Comment by Neppord** [comment]
The brackets `[` are not supposed to be part of the command. They are used as a way to document optional arguments.

**Comment by Neppord** [comment]
The path to the git repo must be a local folder where the repository have previously been cloned to.

**Comment by Neppord** [comment]
If you have any more issues do not hesitate to create a new issue.
