### ISSUE TITLE
Not getting the desired output

### ISSUE THREAD

**Issue by malikdaman24** [Praqma/git-metrics#7]
Tried running the below command after cloning the repository on local, but except for the column details not getting any output in the repo_data.csv file

python git_metrics.py release-lead-time --tag-pattern=v* C:\Users\****\OneDrive\Desktop\try_metrics\new_ones > repo_data.csv

Repository cloned
https://github.com/malikdaman24/new_one

**Comment by Neppord** [comment]
Have you tried with out the `--tag-pattern` flag?

What happens if you just ask for the plot with `--plot` and removing `> repo_data.csv` from the end of the command?

**Comment by Neppord** [comment]
What version of python do you use?

`python --version` should tell you.

**Comment by Neppord** [comment]
it seams like the tags in your repository are on the same commit, so there are no leadtime inbetween them, i dont know what that should mean for the data, but it could be the issue.

**Comment by Neppord** [comment]
Can I close this issue @malikdaman24

**Comment by malikdaman24** [comment]
Yes Samuel, you can close the request
